# Uncomment the next line to define a global platform for your project
# platform :ios, '11.1'

target 'TaskApp' do

  pod 'DropDown'
  

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskApp

  target 'TaskAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaskAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
